# Generated by Django 4.2.7 on 2024-01-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_printbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecartwhitelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.baseproduct'),
        ),
    ]
