# Generated by Django 4.2.7 on 2024-01-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_checkout_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='product',
            new_name='products',
        ),
    ]
