# Generated by Django 4.2.7 on 2024-01-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_checkout_products_checkout_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
