# Generated by Django 4.2.7 on 2024-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_checkout_total_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=100),
        ),
    ]
