# Generated by Django 5.1 on 2024-08-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_checkout_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WomensGlasses',
            new_name='FarmMachinery',
        ),
        migrations.RenameModel(
            old_name='MensCloths',
            new_name='Fertilizers',
        ),
        migrations.RenameModel(
            old_name='WomensHandbags',
            new_name='Fruits',
        ),
        migrations.RenameModel(
            old_name='MensWatches',
            new_name='Grains',
        ),
        migrations.RenameModel(
            old_name='MensShoes',
            new_name='Vegetables',
        ),
    ]
