# Generated by Django 5.1 on 2024-08-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_womensglasses_farmmachinery_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmMachinery',
            new_name='DairyProducts',
        ),
    ]
