# Generated by Django 4.2.4 on 2023-12-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_baseproduct_delete_menscloths_delete_mensshoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensCloths',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseproduct')),
            ],
            bases=('shop.baseproduct',),
        ),
        migrations.CreateModel(
            name='MensShoes',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseproduct')),
            ],
            bases=('shop.baseproduct',),
        ),
        migrations.CreateModel(
            name='MensWatches',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseproduct')),
            ],
            bases=('shop.baseproduct',),
        ),
        migrations.CreateModel(
            name='WomensGlasses',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseproduct')),
            ],
            bases=('shop.baseproduct',),
        ),
        migrations.CreateModel(
            name='WomensHandbags',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.baseproduct')),
            ],
            bases=('shop.baseproduct',),
        ),
    ]
