# Generated by Django 4.2.4 on 2023-12-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_menscloths_mensshoes_menswatches_womensglasses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCartWhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.baseproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basecartwhitelist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
