# Generated by Django 4.2.4 on 2023-12-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_basecartwhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('basecartwhitelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.basecartwhitelist')),
            ],
            bases=('shop.basecartwhitelist',),
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('basecartwhitelist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.basecartwhitelist')),
            ],
            bases=('shop.basecartwhitelist',),
        ),
    ]
