# Generated by Django 4.2.4 on 2023-12-27 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_cart_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Japan', 'Japan')], max_length=100)),
                ('city', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur')], max_length=100)),
                ('address', models.TextField()),
                ('mobile_number', models.IntegerField()),
                ('order_note', models.TextField()),
                ('payment_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('visa', 'Visa'), ('cash', 'Cash')], max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.basecartwhitelist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
